### ISSUE TITLE
Check hangs for a playlist

### ISSUE THREAD

**Issue by MikkoMMM** [axcore/tartube#45]
I'm on the master branch, and after adding a playlist and pressing "Check all", nothing much seems to happen. In the console it just starts looping these kind of lines:
```
2020-01-23 01:58:44 app 7491 dl_timer_callback
2020-01-23 01:58:44 mwn 5248 progress_list_display_dl_stats
2020-01-23 01:58:44 mwn 5493 results_list_update_row
2020-01-23 01:58:44 mwn 5842 output_tab_update_pages
2020-01-23 01:58:44 dld 990 fetch_next_item
2020-01-23 01:58:44 dld 408 check_workers_all_finished
2020-01-23 01:58:44 dld 990 fetch_next_item
2020-01-23 01:58:44 dld 408 check_workers_all_finished
```

**Comment by axcore** [comment]
Can you please check whether this issue still exists in v1.3.048.

**Comment by MikkoMMM** [comment]
In 1.3.048 it doesn't give the looping lines, but after a few of seconds this appears in the console:
```
(tartube:253847): Gtk-CRITICAL **: 18:33:26.946: gtk_tree_model_sort_get_path: assertion 'priv->stamp == iter->stamp' failed

(tartube:253847): Gtk-CRITICAL **: 18:33:26.946: gtk_tree_path_to_string: assertion 'path != NULL' failed
    self.run()
  File "/mnt/lvdata/Downloads/tartube-1.3.048/tartube/downloads.py", line 681, in run
    return_code = self.video_downloader_obj.do_download()
  File "/mnt/lvdata/Downloads/tartube-1.3.048/tartube/downloads.py", line 1557, in do_download
    dl_stat_dict = self.extract_stdout_data(stdout)
  File "/mnt/lvdata/Downloads/tartube-1.3.048/tartube/downloads.py", line 2569, in extract_stdout_data
    self.confirm_sim_video(json_dict)
  File "/mnt/lvdata/Downloads/tartube-1.3.048/tartube/downloads.py", line 2014, in confirm_sim_video
    video_obj = app_obj.create_video_from_download(
  File "/mnt/lvdata/Downloads/tartube-1.3.048/tartube/mainapp.py", line 4225, in create_video_from_download
    video_obj = self.add_video(
  File "/mnt/lvdata/Downloads/tartube-1.3.048/tartube/mainapp.py", line 4802, in add_video
    self.main_win_obj.video_catalogue_update_row(video_obj)
  File "/mnt/lvdata/Downloads/tartube-1.3.048/tartube/mainwin.py", line 4818, in video_catalogue_update_row
    self.video_catalogue_insert_item(video_obj)
  File "/mnt/lvdata/Downloads/tartube-1.3.048/tartube/mainwin.py", line 4878, in video_catalogue_insert_item
    catalogue_item_obj.update_widgets()
  File "/mnt/lvdata/Downloads/tartube-1.3.048/tartube/mainwin.py", line 9464, in update_widgets
    self.update_video_name()
  File "/mnt/lvdata/Downloads/tartube-1.3.048/tartube/mainwin.py", line 9592, in update_video_name
    cgi.escape(
AttributeError: module 'cgi' has no attribute 'escape'
```

Also, downloading doesn't seem to work in 1.3.048 either. In the version preceding it it did. The status is "Waiting" and under Output -> Summary it says:
```
Manager:   Starting download operation
Manager:   Workers: available: 2, total: 2
Thread #1: Downloading 'Short'
Thread #1: Assigned job 'Short'
Manager:   Workers: available: 1, total: 2
```
but nothing is on the two Thread tabs or on Errors / Warnings.

**Comment by MikkoMMM** [comment]
Okay, maybe I spoke too soon. After I was doing some testing with an individual video and pressed Download all, things started happening for the playlist too. But still, I doubt it was working as expected in my previous reply.

**Comment by axcore** [comment]
Ok, this issue occurs because the cgi.escape() function has been removed from Python 3.8.

I am using Python 3.7, and presumably you are using Python 3.8, and that's why you see an error message and I don't.

The issue is fixed for all version of Python in Tartube v1.3.077.
