### ISSUE TITLE
Filter not working in v2.5.210 — errors in video_catalogue_apply_filter

### ISSUE THREAD

**Issue by raafal** [axcore/tartube#784]
**Environment**

- **OS:** Linux, Ubuntu 25.10
- **Python version:** 3.13
- **Tartube version:** v2.5.210 (installed via pip in a venv — newer than the latest GitHub release v2.5.197, so apologies if this has already been addressed)

**Description**

The Filter field in the Video Catalogue doesn't seem to work — pressing Enter raises exceptions instead of filtering the list. Tartube otherwise remains fully functional. I traced it to two issues in `video_catalogue_apply_filter()` in `mainwin.py` and managed to get it working with the changes described below.

---

**Issue 1: Missing None guards on video fields**

Fields like `child_obj.name`, `child_obj.author`, and `child_obj.descrip` can be `None` for some videos (e.g. videos with no description). The filter function calls `.lower().find()` and passes them to `re.search()` without checking for `None` first.

**Traceback (non-regex, line 12719):**

```
Uncaught exception:
Type: <class 'AttributeError'>
Value: 'NoneType' object has no attribute 'lower'
Traceback: File "/home/rafal/venvs/tartube-dev/lib/python3.13/site-packages/tartube/mainwin.py", line 19241, in on_video_catalogue_filter_entry_activated
  self.video_catalogue_apply_filter()
File "/home/rafal/venvs/tartube-dev/lib/python3.13/site-packages/tartube/mainwin.py", line 12719, in video_catalogue_apply_filter
  and child_obj.descrip.lower().find(lower_text) > -1
```

**Traceback (regex, line 12708):**

```
Uncaught exception:
Type: <class 'TypeError'>
Value: expected string or bytes-like object, got 'NoneType'
Traceback: File "/home/rafal/venvs/tartube-dev/lib/python3.13/site-packages/tartube/mainwin.py", line 19241, in on_video_catalogue_filter_entry_activated
  self.video_catalogue_apply_filter()
File "/home/rafal/venvs/tartube-dev/lib/python3.13/site-packages/tartube/mainwin.py", line 12708, in video_catalogue_apply_filter
  and re.search(
    search_text,
    child_obj.author,
    re.IGNORECASE,
  )
File "/usr/lib/python3.13/re/__init__.py", line 177, in search
  return compile(pattern, flags).search(string)
```

**What seemed to fix it:**

For `.lower().find()` calls, adding a `None` check:

```python
and (child_obj.descrip is not None and child_obj.descrip.lower().find(lower_text) > -1)
```

For `re.search()` calls, defaulting `None` to an empty string:

```python
and re.search(search_text, (child_obj.author or ""), re.IGNORECASE)
```

---

**Issue 2: Operator precedence in author/descrip blocks**

After fixing Issue 1, I noticed that filtering with regex and only "Author" checked was also matching videos based on their description, even though "Description" was unchecked.

It looks like the `name` block correctly wraps the regex/non-regex branches in an outer parenthesis:

```python
and (
    (not regex_flag and ...) or (regex_flag and ...)
)
```

But the `author` and `descrip` blocks are missing that outer wrapping, so the `regex_flag` branch ends up as a free-standing `or` that isn't guarded by the corresponding checkbox flag (`catalogue_filter_author_flag` / `catalogue_filter_descrip_flag`).

**What seemed to fix it:**

Adding the missing parentheses to match the `name` block structure, e.g. for `author`:

```python
) or (
    self.app_obj.catalogue_filter_author_flag \
    and child_obj.author is not None \
    and (
        (
            not regex_flag \
            and (child_obj.author is not None and child_obj.author.lower().find(lower_text) > -1)
        ) or (
            regex_flag \
            and re.search(search_text, (child_obj.author or ""), re.IGNORECASE)
        )
    )
)
```

And similarly for the `descrip` block.

---

Thanks for a great tool :)

**Comment by axcore** [comment]
Thanks, the fixes will be in this week's release. 

Checking the whole codebase for problems like Issue 1 is on my to-do list. As for Issue 2, I feel slightly embarrassed about it (because unambiguous operator precedence is normally my favourite thing.)

**Comment by raafal** [comment]
you are doing a great work 🙂
Pozdrawiam,
Rafał

22 May 2026 08:33:34 A S Lewis ***@***.***>:

**Comment by axcore** [comment]
Added in v2.5.231.
